DROP SCHEMA IF EXISTS USER;
CREATE SCHEMA USER;

CREATE TABLE USER.USERS (
  USER_ID  VARCHAR(255) PRIMARY KEY,
  PASSWORD CHAR(60) NOT NULL
);

COMMENT ON TABLE USER.USERS IS 'ユーザー';
COMMENT ON COLUMN USER.USERS.USER_ID IS 'ユーザーID';
COMMENT ON COLUMN USER.USERS.PASSWORD IS 'パスワード';



